### ISSUE TITLE
Left button cannot be used

### ISSUE THREAD

**Issue by Demisemo** [Azzurite/apex-aim-training-configs#1]
F9, F10, F11 do not know the effect, no response

**Comment by Azzurite** [comment]
Hey I don't know how you found this repository, but it will all be explained in the video I will post tomorrow evening :)

You need `sv_cheats` to be settable by you, so you can basically only use F9-F11 on local servers. They are supposed to change some movement variables and your crosshair, that's it.

There should also be no effect on your left mouse button, only your right one.

**Comment by Azzurite** [comment]
I assume this has been resolved.
